name: Backend Tests

on:
  push:
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'

jobs:
  pytest:
    runs-on: ubuntu-latest
    env:
      # Ensure the app and alembic use the same SQLite file inside the workspace
      SQLALCHEMY_DATABASE_URI: sqlite:///backend/data.db
    strategy:
      matrix:
        python: [3.10, 3.11]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          # ensure alembic is available in the runner
          python -m pip install alembic
      - name: Run Alembic migrations
        run: |
          # Ensure alembic is available and run migrations to prepare DB
          alembic -c alembic.ini upgrade head
      - name: Run tests
        run: |
          pytest backend/tests -q