name: Backend Tests

on:
  push:
    paths:
      - "backend/**"
  pull_request:
    paths:
      - "backend/**"

jobs:
  pytest:
    runs-on: ubuntu-latest
    env:
      # Ensure the app and alembic use the same SQLite file inside the workspace
      SQLALCHEMY_DATABASE_URI: sqlite:///backend/data.db
    strategy:
      matrix:
        python: [3.10, 3.11]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
      - name: Run Alembic migrations
        env:
          # make sure alembic reads the same DB URL we want it to use
          SQLALCHEMY_DATABASE_URI: ${{ env.SQLALCHEMY_DATABASE_URI }}
        run: |
          # Ensure alembic is available and run migrations to prepare DB
          alembic -c alembic.ini upgrade head
      - name: Run tests
        run: |
          pytest backend/tests -q